development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 785180609600-ttk5ipel32bms7qhvmk6uj70n8hp4s1i.apps.googleusercontent.com
  google_client_secret: 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